# Generated by Django 3.2.9 on 2021-12-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20211202_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='arrivalTime',
            new_name='arrivalDateTime',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='departureTime',
            new_name='departureDateTime',
        ),
    ]
