# Generated by Django 4.0 on 2021-12-09 14:10

import django.core.validators
from django.db import migrations, models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_agency_ticket_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrivalDateTime',
            field=models.DateTimeField(validators=[tickets.validators.validate_current_date]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure',
            field=models.CharField(max_length=50, validators=[tickets.validators.validate_len, django.core.validators.RegexValidator('^[A-Z][a-z]*(?:\\s[A-Z][a-z]*)*$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departureDateTime',
            field=models.DateTimeField(validators=[tickets.validators.validate_current_date]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(max_length=50, validators=[tickets.validators.validate_len, django.core.validators.RegexValidator('^[A-Z][a-z]*(?:\\s[A-Z][a-z]*)*$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=50, validators=[tickets.validators.validate_len, django.core.validators.RegexValidator('^[A-Z][a-z]*(?:\\s[A-Z][a-z]*)*$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[tickets.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='surname',
            field=models.CharField(max_length=50, validators=[tickets.validators.validate_len, django.core.validators.RegexValidator('^[A-Z][a-z]*(?:\\s[A-Z][a-z]*)*$')]),
        ),
    ]
