# Generated by Django 4.0 on 2021-12-09 14:44
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0005_alter_ticket_arrivaldatetime_alter_ticket_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='arrivalDateTime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='timeFlight',
            field=models.TimeField(default=datetime.time(00, 00, 00)),
            preserve_default=False,
        ),
    ]
