# Generated by Django 4.0 on 2021-12-12 16:43

from django.db import migrations, models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_arrivaldatetime_ticket_timeflight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timeFlight',
            field=models.TimeField(validators=[tickets.validators.validate_limit_min_time]),
        ),
    ]
